# This is a basic workflow to help you get started with Actions

name: main

# Controls when the action will run. 
on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Log stuff from other workflow
        uses: hmarr/debug-action@v2

      # Runs a single command using the runners shell
#       - name: Authenticate to Github token
#         run: gh auth login --with-token < echo ${{ secrets.GITHUB_TOKEN }}
      - name: view repo
        run: gh repo view 

      # Runs a set of commands using the runners shell
      - name: Download Artifact
#         run: gh run download ${{ github.event.workflow_run.id }}
        run: gh run --help
        
      - name: check if file downloaded
        run: ls
  
